name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v3
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pip install -e '.[test]'
        pip install pytest-cov
    - name: Run tests
      run: |
        pytest --cov datasette_indieauth --cov-fail-under=100
    - name: Upload coverage to codecov.io (3.10 only)
      run: bash <(curl -s https://codecov.io/bash)
      if: always() && matrix['python-version'] == '3.10'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: actions/cache@v3
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-deploy-
        restore-keys: |
          ${{ runner.os }}-pip-deploy-
    - name: Install deploy dependencies
      run: |
        pip install datasette datasette-publish-vercel
    - name: Download fixtures.db
      run: |-
        wget https://latest.datasette.io/fixtures.db
    - name: Deploy demo using Vercel
      env:
        NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
      run: |-
        datasette publish vercel fixtures.db \
          --token $NOW_TOKEN \
          --project datasette-indieauth-demo \
          --title "datasette-indieauth demo" \
          --about "simonw/datasette-indieauth" \
          --about_url "https://github.com/simonw/datasette-indieauth" \
          --install "https://github.com/simonw/datasette-indieauth/archive/$GITHUB_SHA.zip"
